[tool.poetry]
name = "cryptoanalytics"
version = "0.1.0"
description = ""
authors = ["anikeenko <dimskay1988@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
