# Generated by Django 4.0.7 on 2022-09-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в сети')),
                ('name', models.TextField(null=True, verbose_name='Имя пользователя')),
                ('surname', models.TextField(null=True, verbose_name='Фамилия пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='MessageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(verbose_name='Отслеживаемая криптовалют')),
                ('coin', models.TextField(verbose_name='В валюте')),
                ('price', models.FloatField(max_length=30, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.profile')),
            ],
            options={
                'verbose_name': 'Сообщение от профиля',
                'verbose_name_plural': 'Сообщения от профилей',
            },
        ),
    ]
