# Generated by Django 4.0.7 on 2022-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в сети')),
                ('name', models.TextField(null=True, verbose_name='Имя пользователя')),
                ('surname', models.TextField(null=True, verbose_name='Фамилия пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
