# Generated by Django 4.1 on 2022-08-31 07:47

import apps.Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=apps.Employees.models.create_invite_code, max_length=8, unique=True),
        ),
    ]
