# Generated by Django 4.0.7 on 2022-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprofile',
            name='coin',
            field=models.TextField(verbose_name='Валюта'),
        ),
    ]
