# Generated by Django 4.0.7 on 2022-09-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(verbose_name='Отслеживаемая криптовалют')),
                ('coin', models.TextField(verbose_name='В валюте')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.profile')),
            ],
            options={
                'verbose_name': 'Сообщение от профиля',
                'verbose_name_plural': 'Сообщения от профилей',
            },
        ),
    ]
