# Generated by Django 4.0 on 2022-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_messageprofile_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageprofile',
            options={'verbose_name': 'Profile message', 'verbose_name_plural': 'Messages from profiles'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='messageprofile',
            name='tracking_status',
            field=models.TextField(default=None, verbose_name='Tracking status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageprofile',
            name='coin',
            field=models.TextField(verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='messageprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='messageprofile',
            name='currency',
            field=models.TextField(verbose_name='Tracked Cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='messageprofile',
            name='price',
            field=models.FloatField(max_length=30, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID user telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(null=True, verbose_name='Surname'),
        ),
    ]
