# Generated by Django 4.0.1 on 2022-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_messageprofile_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprofile',
            name='tracking_status',
            field=models.TextField(null=True, verbose_name='Tracking status'),
        ),
    ]
