# Generated by Django 4.0.7 on 2022-09-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_profile_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.TextField(null=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
