# Generated by Django 4.0.7 on 2022-09-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_profile_surname_alter_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
