# Generated by Django 4.0.1 on 2022-09-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
