# Generated by Django 4.1 on 2022-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0003_alter_coins_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='platforms',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
